name: Maven Build

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11, 17, 21]  # Test with multiple Java versions

    name: Build with Java ${{ matrix.java-version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'  # OpenJDK distribution
        cache: maven

    - name: Build with Maven
      run: mvn clean compile

    - name: Run tests
      run: mvn test

    - name: Package JAR
      run: mvn package

    - name: Verify converter JAR
      run: |
        echo "Checking if converter JAR was created..."
        ls -la target/
        if [ ! -f target/kafka-ssl-jfr-1.0.0.jar ]; then
          echo "Error: Converter JAR not found!"
          exit 1
        fi
        echo "Converter JAR created successfully"

    - name: Verify JMC Agent downloaded
      run: |
        echo "Checking if JMC Agent was downloaded..."
        ls -la target/test-libs/
        if [ ! -f target/test-libs/jmc-agent.jar ]; then
          echo "Error: JMC Agent JAR not found!"
          exit 1
        fi
        echo "JMC Agent JAR downloaded successfully"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      if: matrix.java-version == 11  # Only upload artifact from Java 11 build
      with:
        name: kafka-ssl-jfr-converter
        path: target/kafka-ssl-jfr-*.jar
        retention-days: 30

  code-quality:
    runs-on: ubuntu-latest
    name: Code Quality Check

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'temurin'
        cache: maven

    - name: Run Maven Verify
      run: mvn clean verify

    - name: Check for compiler warnings
      run: mvn clean compile -Dmaven.compiler.showWarnings=true

  dependency-check:
    runs-on: ubuntu-latest
    name: Dependency Security Check

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'temurin'
        cache: maven

    - name: Check for dependency updates
      run: mvn versions:display-dependency-updates

    - name: Analyze dependencies
      run: mvn dependency:analyze